### ISSUE TITLE
can NOT `game.set(.)` in `Empirica.onGameStart()`

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/create-empirica-app#7]
This code:
```javascript
Empirica.onGameStart((game, players) => {
  console.debug("game ", game._id, " started");
  game.set("nOptimalSolutions", 0); // will count how many times they've got the optimal answer
});
```

will throw this error:

```
I20181008-18:01:16.189(-4)? Exception while invoking method 'Players.methods.create' { MongoError: Cannot create field 'nOptimalSolutions' in element {data: []}
I20181008-18:01:16.190(-4)?     at Function.MongoError.create (/Users/amaatouq/.meteor/packages/npm-mongo/.3.0.11.2r10vf.tlqlu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/error.js:45:10)
I20181008-18:01:16.190(-4)?     at toError (/Users/amaatouq/.meteor/packages/npm-mongo/.3.0.11.2r10vf.tlqlu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:149:22)
I20181008-18:01:16.190(-4)?     at /Users/amaatouq/.meteor/packages/npm-mongo/.3.0.11.2r10vf.tlqlu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:1029:39
I20181008-18:01:16.190(-4)?     at /Users/amaatouq/.meteor/packages/npm-mongo/.3.0.11.2r10vf.tlqlu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:544:18
I20181008-18:01:16.190(-4)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20181008-18:01:16.190(-4)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
I20181008-18:01:16.191(-4)?  => awaited here:
I20181008-18:01:16.191(-4)?     at Promise.await (/Users/amaatouq/.meteor/packages/promise/.0.11.1.gy8c7h.yyj0f++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20181008-18:01:16.191(-4)?     at Server.apply (packages/ddp-server/livedata_server.js:1634:14)
I20181008-18:01:16.191(-4)?     at ValidatedMethod.call (packages/mdg:validated-method/validated-method.js:67:30)
I20181008-18:01:16.191(-4)?     at packages/empirica:core/api/player-stages/augment.js:11:18
I20181008-18:01:16.191(-4)?     at Object.set (packages/empirica:core/api/player-stages/augment.js:60:3)
I20181008-18:01:16.191(-4)?     at Empirica.onGameStart (server/callbacks.js:12:8)
I20181008-18:01:16.191(-4)?     at createGameFromLobby (packages/empirica:core/api/games/create.js:331:7)
I20181008-18:01:16.191(-4)?     at Object.GameLobbies.after.update.fetchPrevious (packages/empirica:core/api/game-lobbies/hooks.js:73:5)
I20181008-18:01:16.191(-4)?     at packages/matb33_collection-hooks.js:486:20
I20181008-18:01:16.192(-4)?     at Array.forEach (<anonymous>)
I20181008-18:01:16.192(-4)?     at Function._.each._.forEach (packages/underscore.js:139:11)
I20181008-18:01:16.192(-4)?     at packages/matb33_collection-hooks.js:485:11
I20181008-18:01:16.192(-4)?     at Array.forEach (<anonymous>)
I20181008-18:01:16.192(-4)?     at Function._.each._.forEach (packages/underscore.js:139:11)
I20181008-18:01:16.192(-4)?     at after (packages/matb33_collection-hooks.js:484:9)
I20181008-18:01:16.192(-4)?     at Object.<anonymous> (packages/matb33_collection-hooks.js:505:5)
I20181008-18:01:16.192(-4)?   name: 'MongoError',
I20181008-18:01:16.192(-4)?   message: 'Cannot create field \'nOptimalSolutions\' in element {data: []}',
I20181008-18:01:16.192(-4)?   driver: true,
I20181008-18:01:16.192(-4)?   index: 0,
I20181008-18:01:16.193(-4)?   code: 28,
I20181008-18:01:16.193(-4)?   errmsg: 'Cannot create field \'nOptimalSolutions\' in element {data: []}' }
```

**Comment by amaatouq** [comment]
Actually, it seems that I can't `game.set()` anywhere in the callbacks.
